# Project: PAT_CCF01
# Makefile created by Dev-C++ 5.6.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../CCF认证模拟题/201803/1跳一跳/main.o
LINKOBJ  = ../../CCF认证模拟题/201803/1跳一跳/main.o
LIBS     = -L"C:/Users/59766/Desktop/重要内容/复试准备/华师/专业基础/DEVC++/Dev-Cpp/MinGW32/lib" -static-libgcc
INCS     = -I"C:/Users/59766/Desktop/重要内容/复试准备/华师/专业基础/DEVC++/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Users/59766/Desktop/重要内容/复试准备/华师/专业基础/DEVC++/Dev-Cpp/MinGW32/include"
BIN      = CCF201803-01.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../CCF认证模拟题/201803/1跳一跳/main.o: ../../CCF认证模拟题/201803/1跳一跳/main.cpp
	$(CPP) -c ../../CCF认证模拟题/201803/1跳一跳/main.cpp -o ../../CCF认证模拟题/201803/1跳一跳/main.o $(CXXFLAGS)
